[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.black]
line-length = 88
skip-string-normalization = true
target-version = ["py38"]

[tool.poetry]
name = "urban-meal-delivery"
version = "0.1.0.dev0"

authors = ["Alexander Hess <alexander@webartifex.biz>"]
description = "Optimizing an urban meal delivery platform"
keywords = [
    "data-science",
    "meal-delivery",
    "vehicle-routing-problem",
]
license = "MIT"

readme = "README.md"
homepage = "https://github.com/webartifex/urban-meal-delivery"
repository = "https://github.com/webartifex/urban-meal-delivery"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
# Task Runners
nox = "^2020.5.24"

# Code Formatters
autoflake = "^1.3.1"
black = "^19.10b0"
isort = "^5.2.2"
