name: CI
on: push
jobs:
  fast-tests:
    name: fast (without R)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: pip install nox==2020.5.24
    - run: pip install poetry==1.1.4
    - run: nox -s format lint ci-tests-fast safety docs
  slow-tests:
    name: slow (with R)
    runs-on: ubuntu-latest
    env:
      R_LIBS: .r_libs
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - run: mkdir .r_libs
    - run: sudo apt-get install r-base r-base-dev libcurl4-openssl-dev libxml2-dev patchelf
    - run: R -e "install.packages('forecast')"
    - run: pip install nox==2020.5.24
    - run: pip install poetry==1.1.4
    - run: nox -s ci-tests-slow
